# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x0btestPackage\"!\n\x0cImageDetails\x12\x11\n\tnode_name\x18\x01 \x01(\t\"#\n\rFinishedImage\x12\x12\n\nimage_name\x18\x01 \x01(\t\"\x0e\n\x0cInfraDetails\"\x0c\n\nKeyDetails\"\t\n\x07KeyPair2\xde\x01\n\x0cImageBuilder\x12\x45\n\nBuildImage\x12\x19.testPackage.ImageDetails\x1a\x1a.testPackage.FinishedImage\"\x00\x12\x45\n\x0b\x44\x65ployInfra\x12\x19.testPackage.InfraDetails\x1a\x19.testPackage.InfraDetails\"\x00\x12@\n\rCreateKeyPair\x12\x17.testPackage.KeyDetails\x1a\x14.testPackage.KeyPair\"\x00\x62\x06proto3')



_IMAGEDETAILS = DESCRIPTOR.message_types_by_name['ImageDetails']
_FINISHEDIMAGE = DESCRIPTOR.message_types_by_name['FinishedImage']
_INFRADETAILS = DESCRIPTOR.message_types_by_name['InfraDetails']
_KEYDETAILS = DESCRIPTOR.message_types_by_name['KeyDetails']
_KEYPAIR = DESCRIPTOR.message_types_by_name['KeyPair']
ImageDetails = _reflection.GeneratedProtocolMessageType('ImageDetails', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDETAILS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testPackage.ImageDetails)
  })
_sym_db.RegisterMessage(ImageDetails)

FinishedImage = _reflection.GeneratedProtocolMessageType('FinishedImage', (_message.Message,), {
  'DESCRIPTOR' : _FINISHEDIMAGE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testPackage.FinishedImage)
  })
_sym_db.RegisterMessage(FinishedImage)

InfraDetails = _reflection.GeneratedProtocolMessageType('InfraDetails', (_message.Message,), {
  'DESCRIPTOR' : _INFRADETAILS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testPackage.InfraDetails)
  })
_sym_db.RegisterMessage(InfraDetails)

KeyDetails = _reflection.GeneratedProtocolMessageType('KeyDetails', (_message.Message,), {
  'DESCRIPTOR' : _KEYDETAILS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testPackage.KeyDetails)
  })
_sym_db.RegisterMessage(KeyDetails)

KeyPair = _reflection.GeneratedProtocolMessageType('KeyPair', (_message.Message,), {
  'DESCRIPTOR' : _KEYPAIR,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testPackage.KeyPair)
  })
_sym_db.RegisterMessage(KeyPair)

_IMAGEBUILDER = DESCRIPTOR.services_by_name['ImageBuilder']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEDETAILS._serialized_start=27
  _IMAGEDETAILS._serialized_end=60
  _FINISHEDIMAGE._serialized_start=62
  _FINISHEDIMAGE._serialized_end=97
  _INFRADETAILS._serialized_start=99
  _INFRADETAILS._serialized_end=113
  _KEYDETAILS._serialized_start=115
  _KEYDETAILS._serialized_end=127
  _KEYPAIR._serialized_start=129
  _KEYPAIR._serialized_end=138
  _IMAGEBUILDER._serialized_start=141
  _IMAGEBUILDER._serialized_end=363
# @@protoc_insertion_point(module_scope)
